Initial pr
bloXroute-Labs/aori-integration pull request #1
Opened 2023-12-08 17:13 UTC by tinystarinagalaxy

2023-12-08 18:45 UTC, DimaCantemir requested changes
Good work. A few changes recommended

2023-12-08 18:45 UTC, DimaCantemir commented on governance.go
file is not needed...AFAIK it's related to Atlas

2023-12-08 18:45 UTC, DimaCantemir commented on Dockerfile
you have protobuf compilation docker image but no .proto file

2023-12-08 18:45 UTC, DimaCantemir commented on utils/bx_client.go
> +// NewGRPCClient connects to custom Trader API
Trader API -> Intent Gateway

2023-12-08 18:45 UTC, DimaCantemir commented on governance.go
> +type Governance struct {
Governance -> Solver. and this change needs to be reflected everywhere.

2023-12-08 19:11 UTC, atulsriv commented on Makefile
> +		protoc --go_out=. --go_opt=paths=source_relative  --go-grpc_out=. --go-grpc_opt=paths=source_relative gateway.proto
are these paths correct? just verify that it works if the proto gens are copy/pasted

2023-12-08 19:11 UTC, atulsriv commented on cmd/solver/main.go
> +	//go func() {
delete this as well, don't think we need

2023-12-08 19:12 UTC, atulsriv commented on cmd/solver/main.go
> +var authHeader = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0eXBlIjoiQXBpS2V5IiwiZW1haWwiOiJkYW5pZWwudGFvQGJsb3hyb3V0ZS5jb20iLCJuYW1lIjoiRGFuaWVsIFRhbyIsInJhdGVMaW1pdCI6MTAwLCJpYXQiOjE3MDAwNzcyOTd9.O6S
I don't think we need this file anymore at all, can you delete it?

2023-12-08 19:14 UTC, atulsriv requested changes
just some minor comments

2023-12-11 21:02 UTC, tinystarinagalaxy commented on cmd/dapp/main.go
> +//func main() {
done

2023-12-11 21:02 UTC, tinystarinagalaxy commented on cmd/solver/main.go
> +	//go func() {
done

2023-12-11 21:03 UTC, tinystarinagalaxy commented on cmd/solver/main.go
> +var authHeader = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0eXBlIjoiQXBpS2V5IiwiZW1haWwiOiJkYW5pZWwudGFvQGJsb3hyb3V0ZS5jb20iLCJuYW1lIjoiRGFuaWVsIFRhbyIsInJhdGVMaW1pdCI6MTAwLCJpYXQiOjE3MDAwNzcyOTd9.O6S
what do you mean, this is our solver, we need it for now, for the demo purposes and etc

2023-12-11 21:14 UTC, tinystarinagalaxy commented on governance.go
deleted this file

2023-12-11 21:14 UTC, tinystarinagalaxy commented on governance.go
> +type Governance struct {
deleted this file

2023-12-11 21:15 UTC, tinystarinagalaxy commented on utils/bx_client.go
> +// NewGRPCClient connects to custom Trader API
done

2023-12-11 21:16 UTC, tinystarinagalaxy commented on utils/bx_client.go
> +		ep = "localhost:5005"
added

2023-12-12 17:10 UTC, atulsriv approved these changes

2023-12-12 17:11 UTC, merged